[workspace]
resolver = "2"
members = [
    "crates/molscene-core",
    "crates/molscene-py",
    "crates/molscene-wasm",
    "crates/molscene-render",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kohbanye/molscene"
authors = ["Koh Sakano"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
molscene-core = { path = "crates/molscene-core" }
molscene-render = { path = "crates/molscene-render" }
