"""Type stubs for the Rust extension module `molscene._core`.

Hand-written for v0.1; `pyo3-stub-gen` can generate these once the API settles.
"""

class Scene:
    @staticmethod
    def from_rcsb(id: str, pdb_text: str) -> Scene: ...
    @staticmethod
    def from_inline_pdb(pdb_text: str) -> Scene: ...
    @staticmethod
    def from_inline_sdf(sdf_text: str) -> Scene: ...
    def representation(
        self,
        kind: str,
        selection: Selection,
        color: str | None = ...,
        opacity: float | None = ...,
        scale: float | None = ...,
        radius: float | None = ...,
        text: str | None = ...,
    ) -> None: ...
    def set_center(self, selection: Selection) -> None: ...
    def set_orient(self, selection: Selection) -> None: ...
    def set_color(self, selection: Selection, color: str) -> None: ...
    def set_background(self, color: str) -> None: ...
    # In-place representation editing (index-keyed; see molscene.Representation).
    def num_representations(self) -> int: ...
    def rep_kind(self, index: int) -> str: ...
    def rep_style(
        self, index: int
    ) -> tuple[str | None, float | None, float | None, float | None, str | None]: ...
    def set_rep_style(
        self,
        index: int,
        color: str | None = ...,
        opacity: float | None = ...,
        scale: float | None = ...,
        radius: float | None = ...,
        text: str | None = ...,
    ) -> None: ...
    def rep_selection(self, index: int) -> Selection: ...
    def set_rep_selection(self, index: int, selection: Selection) -> None: ...
    def to_geometry_json(self) -> str: ...

class Selection:
    # Classification macros.
    @staticmethod
    def all() -> Selection: ...
    @staticmethod
    def none() -> Selection: ...
    @staticmethod
    def protein() -> Selection: ...
    @staticmethod
    def nucleic() -> Selection: ...
    @staticmethod
    def ligand() -> Selection: ...
    @staticmethod
    def water() -> Selection: ...
    @staticmethod
    def solvent() -> Selection: ...
    @staticmethod
    def hetero() -> Selection: ...
    @staticmethod
    def backbone() -> Selection: ...
    @staticmethod
    def sidechain() -> Selection: ...
    @staticmethod
    def hydrogen() -> Selection: ...
    # Single-clause predicates.
    @staticmethod
    def chain(id: str) -> Selection: ...
    @staticmethod
    def resn(name: str) -> Selection: ...
    @staticmethod
    def element(symbol: str) -> Selection: ...
    @staticmethod
    def resi(start: int, end: int | None = ...) -> Selection: ...
    @staticmethod
    def b(op: str, value: float) -> Selection: ...
    @staticmethod
    def q(op: str, value: float) -> Selection: ...
    # Aggregation.
    @staticmethod
    def byres(sel: Selection) -> Selection: ...
    @staticmethod
    def bychain(sel: Selection) -> Selection: ...
    @staticmethod
    def bymol(sel: Selection) -> Selection: ...
    # Spatial.
    @staticmethod
    def around(sel: Selection, radius: float) -> Selection: ...
    @staticmethod
    def within(sel: Selection, radius: float) -> Selection: ...
    @staticmethod
    def expand(sel: Selection, radius: float) -> Selection: ...
    @staticmethod
    def beyond(sel: Selection, radius: float) -> Selection: ...
    # Boolean composition.
    def __and__(self, other: Selection) -> Selection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __invert__(self) -> Selection: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
