"""Type stubs for the Rust extension module `molscene._core`.

Hand-written for v0.1; `pyo3-stub-gen` can generate these once the API settles.
"""

SPEC_VERSION: str

class Scene:
    @staticmethod
    def from_rcsb(id: str) -> Scene: ...
    @staticmethod
    def from_inline_pdb(data: str) -> Scene: ...
    def representation(self, kind: str, selection: str, style_json: str) -> None: ...
    def set_center(self, selection: str) -> None: ...
    def to_json(self) -> str: ...

class Selection:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __invert__(self) -> Selection: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
