# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Scene",
    "Selection",
]

@typing.final
class Scene:
    r"""
    A molecular scene. Wraps `molscene_core::Scene`.
    """
    @staticmethod
    def from_rcsb(id: builtins.str, pdb_text: builtins.str) -> Scene:
        r"""
        Build a scene from PDB text fetched for an RCSB `id`.
        """
    @staticmethod
    def from_inline_pdb(pdb_text: builtins.str) -> Scene:
        r"""
        Build a scene from inline PDB text.
        """
    @staticmethod
    def from_inline_sdf(sdf_text: builtins.str) -> Scene:
        r"""
        Build a scene from inline SDF / V2000 molfile text (explicit bond orders).
        """
    def representation(self, kind: builtins.str, selection: Selection, color: typing.Optional[builtins.str] = None, opacity: typing.Optional[builtins.float] = None, scale: typing.Optional[builtins.float] = None, radius: typing.Optional[builtins.float] = None, text: typing.Optional[builtins.str] = None) -> None:
        r"""
        Add a representation over `selection` with optional typed style.
        """
    def set_center(self, selection: Selection) -> None:
        r"""
        Center the camera on a selection.
        """
    def set_orient(self, selection: Selection) -> None:
        r"""
        Orient the view along a selection's principal axes.
        """
    def set_color(self, selection: Selection, color: builtins.str) -> None:
        r"""
        Override the color of a sub-selection (applied on top of the
        representations' schemes, in call order).
        """
    def set_background(self, color: builtins.str) -> None:
        r"""
        Set the scene background color (a named color or `#rrggbb`).
        """
    def num_representations(self) -> builtins.int:
        r"""
        Number of representations added so far.
        """
    def rep_kind(self, index: builtins.int) -> builtins.str:
        r"""
        The kind of representation `index` (e.g. `"cartoon"`).
        """
    def rep_style(self, index: builtins.int) -> tuple[typing.Optional[builtins.str], typing.Optional[builtins.float], typing.Optional[builtins.float], typing.Optional[builtins.float], typing.Optional[builtins.str]]:
        r"""
        The style of representation `index` as
        `(color, opacity, scale, radius, text)`.
        """
    def set_rep_style(self, index: builtins.int, color: typing.Optional[builtins.str] = None, opacity: typing.Optional[builtins.float] = None, scale: typing.Optional[builtins.float] = None, radius: typing.Optional[builtins.float] = None, text: typing.Optional[builtins.str] = None) -> None:
        r"""
        Replace the whole style of representation `index`. A `None` field clears
        that field (back to the representation's default).
        """
    def rep_selection(self, index: builtins.int) -> Selection:
        r"""
        The selection of representation `index`.
        """
    def set_rep_selection(self, index: builtins.int, selection: Selection) -> None:
        r"""
        Re-target representation `index` at a new selection.
        """
    def to_geometry_json(self) -> builtins.str:
        r"""
        Compile to the JSON geometry spec (instanced draw list for the renderer).
        """
    def to_png(self, width: builtins.int = 800, height: builtins.int = 600, ssaa: builtins.int = 2) -> bytes:
        r"""
        Render the scene to PNG bytes with the native GPU rasterizer
        (`molscene-render`, via wgpu). Headless — no window or browser. Returns
        the PNG file contents as `bytes`. Raises `RuntimeError` if no GPU
        (or software fallback) is available.
        """

@typing.final
class Selection:
    r"""
    A selection — a wrapper over a core [`Expr`]. Built through the constructor
    staticmethods (the `ms.select` DSL) and composed with the boolean operators
    (`& | ~`). Valid by construction; there is no selection string.
    """
    @staticmethod
    def all() -> Selection: ...
    @staticmethod
    def none() -> Selection: ...
    @staticmethod
    def protein() -> Selection: ...
    @staticmethod
    def nucleic() -> Selection: ...
    @staticmethod
    def ligand() -> Selection: ...
    @staticmethod
    def water() -> Selection: ...
    @staticmethod
    def solvent() -> Selection: ...
    @staticmethod
    def hetero() -> Selection: ...
    @staticmethod
    def backbone() -> Selection: ...
    @staticmethod
    def sidechain() -> Selection: ...
    @staticmethod
    def hydrogen() -> Selection: ...
    @staticmethod
    def chain(id: builtins.str) -> Selection: ...
    @staticmethod
    def resn(name: builtins.str) -> Selection: ...
    @staticmethod
    def element(symbol: builtins.str) -> Selection: ...
    @staticmethod
    def resi(start: builtins.int, end: typing.Optional[builtins.int] = None) -> Selection: ...
    @staticmethod
    def b(op: builtins.str, value: builtins.float) -> Selection: ...
    @staticmethod
    def q(op: builtins.str, value: builtins.float) -> Selection: ...
    @staticmethod
    def byres(sel: Selection) -> Selection: ...
    @staticmethod
    def bychain(sel: Selection) -> Selection: ...
    @staticmethod
    def bymol(sel: Selection) -> Selection: ...
    @staticmethod
    def around(sel: Selection, radius: builtins.float) -> Selection: ...
    @staticmethod
    def within(sel: Selection, radius: builtins.float) -> Selection: ...
    @staticmethod
    def expand(sel: Selection, radius: builtins.float) -> Selection: ...
    @staticmethod
    def beyond(sel: Selection, radius: builtins.float) -> Selection: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __invert__(self) -> Selection: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

